development:
  sessions:
    default:
      database: user_service_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: user_service_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: user_service_prod
      hosts:
        - localhost:27017